linters:
  enable:
    - errcheck
    - gosec
    - govet
    - nlreturn
    - staticcheck
  disable-all: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - nlreturn
        - errcheck
        - gosec

run:
  timeout: 5m
  