version: "2"

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - nlreturn
    - staticcheck

issues:
  exclude:
    - path: _test\.go
      linters:
        - nlreturn
        - errcheck
        - gosec

run:
  timeout: 5m
